// Code generated by mockery v1.0.0. DO NOT EDIT.

// Copyright 2019 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file.

package websocket

//import mock "github.com/stretchr/testify/mock"
//
//// MockTopicHandlersStorage is an autogenerated mock type for the TopicHandlersStorage type
//type MockTopicHandlersStorage struct {
//	mock.Mock
//}
//
//// GetHandler provides a mock function with given fields: path
//func (_m *MockTopicHandlersStorage) GetHandler(path Path) *TopicHandler {
//	ret := _m.Called(path)
//
//	var r0 *TopicHandler
//	if rf, ok := ret.Get(0).(func(Path) *TopicHandler); ok {
//		r0 = rf(path)
//	} else {
//		if ret.Get(0) != nil {
//			r0 = ret.Get(0).(*TopicHandler)
//		}
//	}
//
//	return r0
//}
//
//// HasHandler provides a mock function with given fields: path
//func (_m *MockTopicHandlersStorage) HasHandler(path Path) bool {
//	ret := _m.Called(path)
//
//	var r0 bool
//	if rf, ok := ret.Get(0).(func(Path) bool); ok {
//		r0 = rf(path)
//	} else {
//		r0 = ret.Get(0).(bool)
//	}
//
//	return r0
//}
//
//// SetTopicHandler provides a mock function with given fields: path, handler
//func (_m *MockTopicHandlersStorage) SetTopicHandler(path Path, handler *TopicHandler) {
//	_m.Called(path, handler)
//}
