// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gorillawebsocket "github.com/gorilla/websocket"
import mock "github.com/stretchr/testify/mock"
import websocket "github.com/proximax-storage/go-xpx-chain-sdk/sdk/websocket"

// MessagePublisher is an autogenerated mock type for the MessagePublisher type
type MessagePublisher struct {
	mock.Mock
}

// PublishSubscribeMessage provides a mock function with given fields: uid, path
func (_m *MessagePublisher) PublishSubscribeMessage(uid string, path websocket.Path) error {
	ret := _m.Called(uid, path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, websocket.Path) error); ok {
		r0 = rf(uid, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishUnsubscribeMessage provides a mock function with given fields: uid, path
func (_m *MessagePublisher) PublishUnsubscribeMessage(uid string, path websocket.Path) error {
	ret := _m.Called(uid, path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, websocket.Path) error); ok {
		r0 = rf(uid, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetConn provides a mock function with given fields: conn
func (_m *MessagePublisher) SetConn(conn *gorillawebsocket.Conn) {
	_m.Called(conn)
}
