// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Router is an autogenerated mock type for the Router type
type Router struct {
	mock.Mock
}

// RouteMessage provides a mock function with given fields: _a0
func (_m *Router) RouteMessage(_a0 []byte) {
	_m.Called(_a0)
}

// SetUid provides a mock function with given fields: _a0
func (_m *Router) SetUid(_a0 string) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewRouter interface {
	mock.TestingT
	Cleanup(func())
}

// NewRouter creates a new instance of Router. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRouter(t mockConstructorTestingTNewRouter) *Router {
	mock := &Router{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
