// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	websocket "github.com/proximax-storage/go-xpx-chain-sdk/sdk/websocket"
	mock "github.com/stretchr/testify/mock"
)

// topicFormatFn is an autogenerated mock type for the topicFormatFn type
type topicFormatFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: info
func (_m *topicFormatFn) Execute(info *sdk.WsMessageInfo) websocket.Path {
	ret := _m.Called(info)

	var r0 websocket.Path
	if rf, ok := ret.Get(0).(func(*sdk.WsMessageInfo) websocket.Path); ok {
		r0 = rf(info)
	} else {
		r0 = ret.Get(0).(websocket.Path)
	}

	return r0
}

type mockConstructorTestingTnewTopicFormatFn interface {
	mock.TestingT
	Cleanup(func())
}

// newTopicFormatFn creates a new instance of topicFormatFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newTopicFormatFn(t mockConstructorTestingTnewTopicFormatFn) *topicFormatFn {
	mock := &topicFormatFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
