// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	websocket "github.com/proximax-storage/go-xpx-chain-sdk/sdk/websocket"
	mock "github.com/stretchr/testify/mock"
)

// Topic is an autogenerated mock type for the Topic type
type Topic struct {
	mock.Mock
}

// Format provides a mock function with given fields: info
func (_m *Topic) Format(info *sdk.WsMessageInfo) websocket.Path {
	ret := _m.Called(info)

	var r0 websocket.Path
	if rf, ok := ret.Get(0).(func(*sdk.WsMessageInfo) websocket.Path); ok {
		r0 = rf(info)
	} else {
		r0 = ret.Get(0).(websocket.Path)
	}

	return r0
}
