// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// blockchainInt64 is an autogenerated mock type for the blockchainInt64 type
type blockchainInt64 struct {
	mock.Mock
}

// toArray provides a mock function with given fields:
func (_m *blockchainInt64) toArray() [2]uint32 {
	ret := _m.Called()

	var r0 [2]uint32
	if rf, ok := ret.Get(0).(func() [2]uint32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([2]uint32)
		}
	}

	return r0
}

// toLittleEndian provides a mock function with given fields:
func (_m *blockchainInt64) toLittleEndian() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

type mockConstructorTestingTnewBlockchainInt64 interface {
	mock.TestingT
	Cleanup(func())
}

// newBlockchainInt64 creates a new instance of blockchainInt64. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newBlockchainInt64(t mockConstructorTestingTnewBlockchainInt64) *blockchainInt64 {
	mock := &blockchainInt64{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
