// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	mock "github.com/stretchr/testify/mock"
)

// CosignatureMapperFn is an autogenerated mock type for the CosignatureMapperFn type
type CosignatureMapperFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: m
func (_m *CosignatureMapperFn) Execute(m []byte) (*sdk.SignerInfo, error) {
	ret := _m.Called(m)

	var r0 *sdk.SignerInfo
	if rf, ok := ret.Get(0).(func([]byte) *sdk.SignerInfo); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sdk.SignerInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCosignatureMapperFn interface {
	mock.TestingT
	Cleanup(func())
}

// NewCosignatureMapperFn creates a new instance of CosignatureMapperFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCosignatureMapperFn(t mockConstructorTestingTNewCosignatureMapperFn) *CosignatureMapperFn {
	mock := &CosignatureMapperFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
