// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"

// CosignatureMapper is an autogenerated mock type for the CosignatureMapper type
type CosignatureMapper struct {
	mock.Mock
}

// MapCosignature provides a mock function with given fields: m
func (_m *CosignatureMapper) MapCosignature(m []byte) (*sdk.SignerInfo, error) {
	ret := _m.Called(m)

	var r0 *sdk.SignerInfo
	if rf, ok := ret.Get(0).(func([]byte) *sdk.SignerInfo); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sdk.SignerInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
