// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	mock "github.com/stretchr/testify/mock"
)

// DriveStateMapper is an autogenerated mock type for the DriveStateMapper type
type DriveStateMapper struct {
	mock.Mock
}

// MapDriveState provides a mock function with given fields: m
func (_m *DriveStateMapper) MapDriveState(m []byte) (*sdk.DriveStateInfo, error) {
	ret := _m.Called(m)

	var r0 *sdk.DriveStateInfo
	if rf, ok := ret.Get(0).(func([]byte) *sdk.DriveStateInfo); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sdk.DriveStateInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDriveStateMapper interface {
	mock.TestingT
	Cleanup(func())
}

// NewDriveStateMapper creates a new instance of DriveStateMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDriveStateMapper(t mockConstructorTestingTNewDriveStateMapper) *DriveStateMapper {
	mock := &DriveStateMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
