// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	mock "github.com/stretchr/testify/mock"
)

// PartialAddedMapper is an autogenerated mock type for the PartialAddedMapper type
type PartialAddedMapper struct {
	mock.Mock
}

// MapPartialAdded provides a mock function with given fields: m
func (_m *PartialAddedMapper) MapPartialAdded(m []byte) (sdk.Transaction, error) {
	ret := _m.Called(m)

	var r0 sdk.Transaction
	if rf, ok := ret.Get(0).(func([]byte) sdk.Transaction); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sdk.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
