// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	mock "github.com/stretchr/testify/mock"
)

// PartialAddedMapper is an autogenerated mock type for the PartialAddedMapper type
type PartialAddedMapper struct {
	mock.Mock
}

// MapPartialAdded provides a mock function with given fields: m
func (_m *PartialAddedMapper) MapPartialAdded(m []byte) (sdk.Transaction, error) {
	ret := _m.Called(m)

	var r0 sdk.Transaction
	if rf, ok := ret.Get(0).(func([]byte) sdk.Transaction); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sdk.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPartialAddedMapper interface {
	mock.TestingT
	Cleanup(func())
}

// NewPartialAddedMapper creates a new instance of PartialAddedMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPartialAddedMapper(t mockConstructorTestingTNewPartialAddedMapper) *PartialAddedMapper {
	mock := &PartialAddedMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
