// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	mock "github.com/stretchr/testify/mock"
)

// StatusMapper is an autogenerated mock type for the StatusMapper type
type StatusMapper struct {
	mock.Mock
}

// MapStatus provides a mock function with given fields: m
func (_m *StatusMapper) MapStatus(m []byte) (*sdk.StatusInfo, error) {
	ret := _m.Called(m)

	var r0 *sdk.StatusInfo
	if rf, ok := ret.Get(0).(func([]byte) *sdk.StatusInfo); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sdk.StatusInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
