// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	mock "github.com/stretchr/testify/mock"
)

// transactionDto is an autogenerated mock type for the transactionDto type
type transactionDto struct {
	mock.Mock
}

// toStruct provides a mock function with given fields: _a0
func (_m *transactionDto) toStruct(_a0 *sdk.Hash) (sdk.Transaction, error) {
	ret := _m.Called(_a0)

	var r0 sdk.Transaction
	if rf, ok := ret.Get(0).(func(*sdk.Hash) sdk.Transaction); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sdk.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*sdk.Hash) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
