// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	mock "github.com/stretchr/testify/mock"
)

// UnconfirmedRemovedMapperFn is an autogenerated mock type for the UnconfirmedRemovedMapperFn type
type UnconfirmedRemovedMapperFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: m
func (_m *UnconfirmedRemovedMapperFn) Execute(m []byte) (*sdk.UnconfirmedRemoved, error) {
	ret := _m.Called(m)

	var r0 *sdk.UnconfirmedRemoved
	if rf, ok := ret.Get(0).(func([]byte) *sdk.UnconfirmedRemoved); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sdk.UnconfirmedRemoved)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUnconfirmedRemovedMapperFn interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnconfirmedRemovedMapperFn creates a new instance of UnconfirmedRemovedMapperFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnconfirmedRemovedMapperFn(t mockConstructorTestingTNewUnconfirmedRemovedMapperFn) *UnconfirmedRemovedMapperFn {
	mock := &UnconfirmedRemovedMapperFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
