// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	mock "github.com/stretchr/testify/mock"
)

// UnconfirmedRemovedMapper is an autogenerated mock type for the UnconfirmedRemovedMapper type
type UnconfirmedRemovedMapper struct {
	mock.Mock
}

// MapUnconfirmedRemoved provides a mock function with given fields: m
func (_m *UnconfirmedRemovedMapper) MapUnconfirmedRemoved(m []byte) (*sdk.UnconfirmedRemoved, error) {
	ret := _m.Called(m)

	var r0 *sdk.UnconfirmedRemoved
	if rf, ok := ret.Get(0).(func([]byte) *sdk.UnconfirmedRemoved); ok {
		r0 = rf(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sdk.UnconfirmedRemoved)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUnconfirmedRemovedMapper interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnconfirmedRemovedMapper creates a new instance of UnconfirmedRemovedMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnconfirmedRemovedMapper(t mockConstructorTestingTNewUnconfirmedRemovedMapper) *UnconfirmedRemovedMapper {
	mock := &UnconfirmedRemovedMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
