// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	mock "github.com/stretchr/testify/mock"
)

// BlockHandler is an autogenerated mock type for the BlockHandler type
type BlockHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *BlockHandler) Execute(_a0 *sdk.BlockInfo) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*sdk.BlockInfo) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewBlockHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewBlockHandler creates a new instance of BlockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBlockHandler(t mockConstructorTestingTNewBlockHandler) *BlockHandler {
	mock := &BlockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
