// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	sdk "github.com/proximax-storage/go-xpx-chain-sdk/sdk"
	subscribers "github.com/proximax-storage/go-xpx-chain-sdk/sdk/websocket/subscribers"
	mock "github.com/stretchr/testify/mock"
)

// UnconfirmedAdded is an autogenerated mock type for the UnconfirmedAdded type
type UnconfirmedAdded struct {
	mock.Mock
}

// AddHandlers provides a mock function with given fields: handle, handlers
func (_m *UnconfirmedAdded) AddHandlers(handle *sdk.TransactionChannelHandle, handlers ...subscribers.UnconfirmedAddedHandler) error {
	_va := make([]interface{}, len(handlers))
	for _i := range handlers {
		_va[_i] = handlers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, handle)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sdk.TransactionChannelHandle, ...subscribers.UnconfirmedAddedHandler) error); ok {
		r0 = rf(handle, handlers...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetHandlers provides a mock function with given fields: handle
func (_m *UnconfirmedAdded) GetHandlers(handle *sdk.TransactionChannelHandle) []*subscribers.UnconfirmedAddedHandler {
	ret := _m.Called(handle)

	var r0 []*subscribers.UnconfirmedAddedHandler
	if rf, ok := ret.Get(0).(func(*sdk.TransactionChannelHandle) []*subscribers.UnconfirmedAddedHandler); ok {
		r0 = rf(handle)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*subscribers.UnconfirmedAddedHandler)
		}
	}

	return r0
}

// GetHandles provides a mock function with given fields:
func (_m *UnconfirmedAdded) GetHandles() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// HasHandlers provides a mock function with given fields: handle
func (_m *UnconfirmedAdded) HasHandlers(handle *sdk.TransactionChannelHandle) bool {
	ret := _m.Called(handle)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*sdk.TransactionChannelHandle) bool); ok {
		r0 = rf(handle)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RemoveHandlers provides a mock function with given fields: handle, handlers
func (_m *UnconfirmedAdded) RemoveHandlers(handle *sdk.TransactionChannelHandle, handlers ...*subscribers.UnconfirmedAddedHandler) bool {
	_va := make([]interface{}, len(handlers))
	for _i := range handlers {
		_va[_i] = handlers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, handle)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*sdk.TransactionChannelHandle, ...*subscribers.UnconfirmedAddedHandler) bool); ok {
		r0 = rf(handle, handlers...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
