name: build tools

on: 
  push:
    branches:
    - 'develop'
    - 'master'
    - 'main'
  pull_request:
    branches:
    - 'develop'
    - 'master'
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          # - '1.19'
          # - '1.20'
          - '1.21.x'
        tool:
          - 'liquidity_provider'
          - 'replicator_onboarding'
          - 'transfer'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: build ${{ matrix.tool}}
        working-directory: tools/${{ matrix.tool}}
        run: go mod tidy && go build .
      
      - name: Upload build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tool }}-binary
          path: tools/${{ matrix.tool}}/${{ matrix.tool }}
